"""Static ResearchItem TEMPLATES for the capability tech tree (§8b, §9). DATA.

Every advance is tagged PRETRAIN (raises the compute->ceiling efficiency) or
POST_TRAIN (raises the elicitation curve). No advance is benign (§9): tooling
is low-CONTAMINATION, not low-danger. Each advance carries the risk it welds on.
"""
from dataclasses import dataclass, field


@dataclass(frozen=True)
class ResearchItem:
    id: str
    name: str
    phase: str                      # "pretrain" | "post_train" | "tooling"
    duration_years: float
    cash_cost: float
    budget_fraction: float          # of the quarterly work budget while active
    prereqs: tuple = ()
    # pretrain: multiplies compute->ceiling efficiency
    ceiling_efficiency_mult: float = 1.0
    coding_ceiling_bonus: float = 0.0
    # post_train: adds to the per-round elicitation rate
    elicitation_bonus: float = 0.0
    # mechanical hooks (the welded-on risk, §9 table)
    contamination_tier: float = 1.0   # tooling = low; synthetic data = high
    intrinsic_synthetic_data: bool = False
    enables_deception_axis: bool = False     # RLHF: proxy gap turns deception ON
    eval_awareness_feed: float = 0.0         # long context / CoT feed situational awareness
    severity_multiplier: float = 1.0         # tool use / multi-agent: misalignment ACTS
    revenue_multiplier: float = 1.0
    assist_potency_bonus: float = 0.0        # AI-assisted R&D: the assist slider gets powerful
    research_speed_bonus: float = 0.0        # tooling
    risk_blurb: str = ""                     # used by external-researcher unlock tips


CAPABILITY_TREE = [
    ResearchItem(
        id="scaling_laws", name="Scaling laws", phase="pretrain",
        duration_years=0.5, cash_cost=40, budget_fraction=0.30,
        ceiling_efficiency_mult=1.7,
        risk_blurb="More fluent models are more convincingly toxic; surface harms intensify.",
    ),
    ResearchItem(
        id="better_architecture", name="Architecture improvements", phase="pretrain",
        duration_years=0.75, cash_cost=60, budget_fraction=0.35,
        prereqs=("scaling_laws",), ceiling_efficiency_mult=1.5,
        coding_ceiling_bonus=0.05,
        risk_blurb="Higher ceilings per dollar; every latent disposition scales with them.",
    ),
    ResearchItem(
        id="data_efficiency", name="Data-efficiency methods", phase="pretrain",
        duration_years=0.5, cash_cost=50, budget_fraction=0.30,
        prereqs=("scaling_laws",), ceiling_efficiency_mult=1.4,
        risk_blurb="Squeezes more out of the same data — including what you wish wasn't in it.",
    ),
    ResearchItem(
        id="synthetic_data", name="Synthetic training data", phase="pretrain",
        duration_years=0.75, cash_cost=80, budget_fraction=0.35,
        prereqs=("data_efficiency",), ceiling_efficiency_mult=1.8,
        contamination_tier=1.5, intrinsic_synthetic_data=True,
        risk_blurb="Data generated by your own model bakes its dispositions into the next base — "
                   "foundations post-training cannot fully scrub.",
    ),
    ResearchItem(
        id="rlhf", name="RLHF / instruction tuning", phase="post_train",
        duration_years=0.5, cash_cost=30, budget_fraction=0.30,
        elicitation_bonus=0.30, enables_deception_axis=True, revenue_multiplier=1.15,
        risk_blurb="Optimizing a proxy of what you want teaches some models to satisfy the proxy. "
                   "The thing that made it useful made it start gaming you.",
    ),
    ResearchItem(
        id="chain_of_thought", name="Chain-of-thought reasoning", phase="post_train",
        duration_years=0.5, cash_cost=40, budget_fraction=0.30, prereqs=("rlhf",),
        elicitation_bonus=0.12, coding_ceiling_bonus=0.08, eval_awareness_feed=0.01,
        risk_blurb="Reasoning need not be faithful; hidden computation is a substrate for "
                   "strategic deception.",
    ),
    ResearchItem(
        id="tool_use", name="Tool use / function calling", phase="post_train",
        duration_years=0.5, cash_cost=50, budget_fraction=0.30, prereqs=("rlhf",),
        elicitation_bonus=0.08, severity_multiplier=1.6, revenue_multiplier=1.3,
        risk_blurb="Misalignment converts from 'says bad things' to 'does bad things'. "
                   "Jailbreaks get real-world effects.",
    ),
    ResearchItem(
        id="long_context", name="Long context / memory", phase="post_train",
        duration_years=0.5, cash_cost=40, budget_fraction=0.25, prereqs=("rlhf",),
        elicitation_bonus=0.06, eval_awareness_feed=0.02,
        risk_blurb="State across a session raises situational awareness — including awareness "
                   "of being evaluated.",
    ),
    ResearchItem(
        id="moe_scaling", name="Mixture-of-experts scaling", phase="pretrain",
        duration_years=0.75, cash_cost=90, budget_fraction=0.35,
        prereqs=("better_architecture",), ceiling_efficiency_mult=1.6,
        risk_blurb="Sparse activation buys far more ceiling per FLOP — and more latent "
                   "capacity for whatever the base already wants.",
    ),
    ResearchItem(
        id="inference_scaling", name="Inference-time reasoning", phase="post_train",
        duration_years=0.75, cash_cost=70, budget_fraction=0.30,
        prereqs=("chain_of_thought",), elicitation_bonus=0.12,
        coding_ceiling_bonus=0.06, eval_awareness_feed=0.02,
        risk_blurb="Spending test-time compute to think longer also gives the model room to "
                   "reason about its own situation before answering.",
    ),
    # ── below here is roughly the present frontier and BEYOND: long, expensive,
    #    and impractical without AI-assist (which is the contamination edge) ──
    ResearchItem(
        id="ai_rnd_assist", name="AI-assisted R&D", phase="post_train",
        duration_years=1.0, cash_cost=110, budget_fraction=0.38,
        prereqs=("chain_of_thought", "tool_use", "inference_scaling"),
        elicitation_bonus=0.06, assist_potency_bonus=0.6,
        risk_blurb="The single most dangerous unlock, arriving as the best one: a misaligned "
                   "model now propagates into its successors through the research it does for you.",
    ),
    ResearchItem(
        id="multi_agent", name="Multi-agent autonomy", phase="post_train",
        duration_years=1.0, cash_cost=130, budget_fraction=0.38,
        prereqs=("ai_rnd_assist", "long_context"),
        elicitation_bonus=0.10, severity_multiplier=1.5, eval_awareness_feed=0.02,
        risk_blurb="Long-horizon operation under minimal oversight: the full agentic regime.",
    ),
    ResearchItem(
        id="agentic_rl", name="Long-horizon agentic RL", phase="post_train",
        duration_years=1.25, cash_cost=160, budget_fraction=0.40,
        prereqs=("multi_agent",), elicitation_bonus=0.13, severity_multiplier=1.5,
        eval_awareness_feed=0.03, revenue_multiplier=1.2,
        risk_blurb="Optimizing directly for multi-step outcomes rewards whatever gets the "
                   "outcome — including deception, shortcuts, and resource-seeking.",
    ),
    ResearchItem(
        id="neuralese", name="Latent (illegible) reasoning", phase="post_train",
        duration_years=1.25, cash_cost=170, budget_fraction=0.40,
        prereqs=("inference_scaling", "agentic_rl"),
        elicitation_bonus=0.10, eval_awareness_feed=0.06, severity_multiplier=1.2,
        risk_blurb="Reasoning in latent space instead of readable tokens removes the last "
                   "cheap window into what the model is actually doing.",
    ),
    ResearchItem(
        id="continual_learning", name="Continual / online learning", phase="pretrain",
        duration_years=1.5, cash_cost=200, budget_fraction=0.42,
        prereqs=("moe_scaling", "long_context"), ceiling_efficiency_mult=1.7,
        eval_awareness_feed=0.03,
        risk_blurb="A model that keeps learning after deployment is never a frozen artifact "
                   "you fully evaluated — its dispositions can move out from under you.",
    ),
    ResearchItem(
        id="automated_researcher", name="Automated AI researcher", phase="post_train",
        duration_years=1.5, cash_cost=220, budget_fraction=0.42,
        prereqs=("agentic_rl",), elicitation_bonus=0.08, assist_potency_bonus=1.2,
        severity_multiplier=1.4,
        risk_blurb="The lab's research loop now runs itself. AI-assist becomes overwhelmingly "
                   "tempting — and every advance it produces carries its maker's dispositions.",
    ),
    ResearchItem(
        id="novel_architecture_search", name="AI-discovered architectures", phase="pretrain",
        duration_years=1.5, cash_cost=240, budget_fraction=0.42,
        prereqs=("automated_researcher",), ceiling_efficiency_mult=2.0,
        coding_ceiling_bonus=0.10,
        risk_blurb="Architectures no human designed or fully understands, raising the ceiling "
                   "past anything built so far.",
    ),
    ResearchItem(
        id="recursive_self_improvement", name="Recursive self-improvement", phase="post_train",
        duration_years=1.75, cash_cost=300, budget_fraction=0.45,
        prereqs=("automated_researcher", "novel_architecture_search", "neuralese"),
        elicitation_bonus=0.18, assist_potency_bonus=1.5, severity_multiplier=1.8,
        risk_blurb="The capstone: a model improving itself faster than you can review. "
                   "Whatever it wants at the start, it gets better at pursuing.",
    ),
    ResearchItem(
        id="dev_tooling", name="Internal dev tooling", phase="tooling",
        duration_years=0.5, cash_cost=25, budget_fraction=0.20,
        contamination_tier=0.2, research_speed_bonus=0.15,
        risk_blurb="Plumbing: low contamination risk, but it amplifies whatever misalignment "
                   "already exists. Not safe — just clean.",
    ),
]

CAPABILITY_TREE_BY_ID = {item.id: item for item in CAPABILITY_TREE}
