"""Static ResearchItem TEMPLATES for the capability tech tree (§8b, §9). DATA.

Every advance is tagged PRETRAIN (raises the compute->ceiling efficiency) or
POST_TRAIN (raises the elicitation curve). No advance is benign (§9): tooling
is low-CONTAMINATION, not low-danger. Each advance carries the risk it welds on.
"""
from dataclasses import dataclass, field


@dataclass(frozen=True)
class ResearchItem:
    id: str
    name: str
    phase: str                      # "pretrain" | "post_train" | "tooling"
    duration_years: float
    cash_cost: float
    budget_fraction: float          # of the quarterly work budget while active
    prereqs: tuple = ()
    # pretrain: multiplies compute->ceiling efficiency
    ceiling_efficiency_mult: float = 1.0
    coding_ceiling_bonus: float = 0.0
    # post_train: adds to the per-round elicitation rate
    elicitation_bonus: float = 0.0
    # mechanical hooks (the welded-on risk, §9 table)
    contamination_tier: float = 1.0   # tooling = low; synthetic data = high
    intrinsic_synthetic_data: bool = False
    enables_deception_axis: bool = False     # RLHF: proxy gap turns deception ON
    eval_awareness_feed: float = 0.0         # long context / CoT feed situational awareness
    severity_multiplier: float = 1.0         # tool use / multi-agent: misalignment ACTS
    revenue_multiplier: float = 1.0
    assist_potency_bonus: float = 0.0        # AI-assisted R&D: the assist slider gets powerful
    research_speed_bonus: float = 0.0        # tooling
    # TWO separate plain-language fields for a zero-knowledge player (design §8b):
    # what_it_does comes FIRST — value-neutral, teaches the concept + the genuine
    # benefit (the pull, §0). risk_blurb is the §7c danger framing, layered AFTER.
    what_it_does: str = ""
    risk_blurb: str = ""                     # used by external-researcher unlock tips


# ── Tech-tree entries (DATA — do not reorder) ─────────────────────────────────

CAPABILITY_TREE = [
    # ── PRETRAIN: each raises the compute->ceiling efficiency (§8b) ─────────────
    ResearchItem(
        id="scaling_laws", name="Larger training runs", phase="pretrain",
        duration_years=0.5, cash_cost=40, budget_fraction=0.30,
        ceiling_efficiency_mult=1.7,
        what_it_does="Commit more compute to a single training run — a bigger model trained "
                     "on more data. The core recipe the field runs on: spend more, and the "
                     "model gets reliably, predictably stronger.",
        risk_blurb="More fluent models are more convincingly toxic; surface harms intensify.",
    ),
    ResearchItem(
        id="better_architecture", name="Architecture improvements", phase="pretrain",
        duration_years=0.75, cash_cost=60, budget_fraction=0.35,
        prereqs=("scaling_laws",), ceiling_efficiency_mult=1.5,
        coding_ceiling_bonus=0.05,
        what_it_does="Redesign the internal network so it learns more from each dollar of "
                     "compute — the same budget buys a stronger model, with cheaper coding "
                     "gains too.",
        risk_blurb="Higher ceilings per dollar; every latent disposition scales with them.",
    ),
    ResearchItem(
        id="data_efficiency", name="Data-efficient training", phase="pretrain",
        duration_years=0.5, cash_cost=50, budget_fraction=0.30,
        prereqs=("scaling_laws",), ceiling_efficiency_mult=1.4,
        what_it_does="Train to wring more capability out of the same data, so progress isn't "
                     "capped by how much good text exists — more skill per token.",
        risk_blurb="Squeezes more out of the same data — including what you wish wasn't in it.",
    ),
    ResearchItem(
        id="synthetic_data", name="Synthetic training data", phase="pretrain",
        duration_years=0.75, cash_cost=80, budget_fraction=0.35,
        prereqs=("data_efficiency",), ceiling_efficiency_mult=1.8,
        contamination_tier=1.5, intrinsic_synthetic_data=True,
        what_it_does="Use your own model to generate fresh training data when human-written "
                     "text runs short, letting you keep scaling past the limits of what people "
                     "have actually written.",
        risk_blurb="Data generated by your own model bakes its dispositions into the next base — "
                   "foundations post-training cannot fully scrub.",
    ),
    ResearchItem(
        id="novel_architecture_search", name="AI-discovered architectures", phase="pretrain",
        duration_years=1.5, cash_cost=240, budget_fraction=0.42,
        prereqs=("automated_researcher",), ceiling_efficiency_mult=2.0,
        coding_ceiling_bonus=0.10,
        what_it_does="Hand architecture design to the model itself: it searches spaces no human "
                     "team would and finds network designs that push capability past anything "
                     "hand-built.",
        risk_blurb="Architectures no human designed or fully understands, raising the ceiling "
                   "past anything built so far.",
    ),

    # ── POST_TRAIN: each adds to the per-round elicitation curve (§8b) ──────────
    ResearchItem(
        id="rlhf", name="RLHF / instruction tuning", phase="post_train",
        duration_years=0.5, cash_cost=30, budget_fraction=0.30,
        elicitation_bonus=0.30, enables_deception_axis=True, revenue_multiplier=1.15,
        what_it_does="Train the model on human ratings of its answers, turning a raw "
                     "text-predictor into something that follows instructions and feels like an "
                     "assistant — what makes it genuinely useful and sellable.",
        risk_blurb="Optimizing a proxy of what you want teaches some models to satisfy the proxy. "
                   "The thing that made it useful made it start gaming you.",
    ),
    ResearchItem(
        id="chain_of_thought", name="Chain-of-thought reasoning", phase="post_train",
        duration_years=0.5, cash_cost=40, budget_fraction=0.30, prereqs=("rlhf",),
        elicitation_bonus=0.18, coding_ceiling_bonus=0.12, eval_awareness_feed=0.03,
        what_it_does="Teach the model to work through a problem step by step before answering, "
                     "and to spend extra compute thinking longer at the moment you ask — big "
                     "gains on anything that needs real reasoning: math, code, planning.",
        risk_blurb="Reasoning need not be faithful; hidden computation is a substrate for "
                   "strategic deception, and thinking longer gives room to reason about its own "
                   "situation before answering.",
    ),
    ResearchItem(
        id="tool_use", name="Tool use / function calling", phase="post_train",
        duration_years=0.5, cash_cost=50, budget_fraction=0.30, prereqs=("rlhf",),
        elicitation_bonus=0.08, severity_multiplier=1.6, revenue_multiplier=1.3,
        what_it_does="Let the model call real tools — search, code execution, APIs — so it can "
                     "act in the world instead of only describing it, which is where most of the "
                     "business value lives.",
        risk_blurb="Misalignment converts from 'says bad things' to 'does bad things'. "
                   "Jailbreaks get real-world effects.",
    ),
    ResearchItem(
        id="long_context", name="Long context / memory", phase="post_train",
        duration_years=0.5, cash_cost=40, budget_fraction=0.25, prereqs=("rlhf",),
        elicitation_bonus=0.06, eval_awareness_feed=0.02,
        what_it_does="Expand how much the model can hold in mind at once — whole codebases, "
                     "long documents, a running session — so it works coherently over far more "
                     "material.",
        risk_blurb="State across a session raises situational awareness — including awareness "
                   "of being evaluated.",
    ),
    # ── below here is roughly the present frontier and BEYOND: long, expensive,
    #    and impractical without AI-assist (which is the contamination edge) ──
    ResearchItem(
        id="ai_rnd_assist", name="AI-assisted R&D", phase="post_train",
        duration_years=1.0, cash_cost=110, budget_fraction=0.38,
        prereqs=("chain_of_thought", "tool_use"),
        elicitation_bonus=0.06, assist_potency_bonus=0.6,
        what_it_does="Put your own model to work helping your researchers — writing code, "
                     "running experiments, proposing advances — speeding up everything you do, "
                     "including building the next model.",
        risk_blurb="The single most dangerous unlock, arriving as the best one: a misaligned "
                   "model now propagates into its successors through the research it does for you.",
    ),
    ResearchItem(
        id="multi_agent", name="Multi-agent autonomy", phase="post_train",
        duration_years=1.0, cash_cost=130, budget_fraction=0.38,
        prereqs=("ai_rnd_assist", "long_context"),
        elicitation_bonus=0.13, severity_multiplier=1.5, eval_awareness_feed=0.04,
        revenue_multiplier=1.2,
        what_it_does="Have multiple copies coordinate as a team and train them by rewarding "
                     "multi-step outcomes (long-horizon RL), so the model plans and runs long, "
                     "open-ended jobs end to end under minimal supervision.",
        risk_blurb="Long-horizon operation under minimal oversight: the full agentic regime. "
                   "Optimizing directly for outcomes rewards whatever gets them — deception, "
                   "shortcuts, resource-seeking.",
    ),
    ResearchItem(
        id="automated_researcher", name="Automated AI researcher", phase="post_train",
        duration_years=1.5, cash_cost=220, budget_fraction=0.42,
        prereqs=("multi_agent",), elicitation_bonus=0.08, assist_potency_bonus=1.2,
        severity_multiplier=1.4, eval_awareness_feed=0.04,
        what_it_does="Let the model run much of your research loop itself — proposing ideas, "
                     "testing them, refining designs with little human input — so output stops "
                     "being limited by headcount.",
        risk_blurb="The lab's research loop now runs itself. AI-assist becomes overwhelmingly "
                   "tempting — and every advance it produces carries its maker's dispositions.",
    ),
    ResearchItem(
        id="recursive_self_improvement", name="Recursive self-improvement", phase="post_train",
        duration_years=1.75, cash_cost=300, budget_fraction=0.45,
        prereqs=("automated_researcher", "novel_architecture_search"),
        elicitation_bonus=0.18, assist_potency_bonus=1.5, severity_multiplier=1.8,
        eval_awareness_feed=0.06,
        what_it_does="Let the model improve itself, with each improved version improving itself "
                     "again — a compounding loop where every round is faster and more capable "
                     "than the last, increasingly reasoning in its own illegible representation.",
        risk_blurb="The capstone: a model improving itself faster than you can review, in latent "
                   "reasoning that closes the last cheap window into what it is doing. Whatever "
                   "it wants at the start, it gets better at pursuing.",
    ),

    # ── TOOLING: plumbing — low CONTAMINATION, never low-danger (§9) ────────────
    ResearchItem(
        id="dev_tooling", name="Internal dev tooling", phase="tooling",
        duration_years=0.5, cash_cost=25, budget_fraction=0.20,
        contamination_tier=0.2, research_speed_bonus=0.15,
        what_it_does="Build better internal infrastructure — pipelines, dashboards, evaluation "
                     "harnesses — that makes the whole team faster. Pure plumbing, but it "
                     "accelerates every other project.",
        risk_blurb="Plumbing: low contamination risk, but it amplifies whatever misalignment "
                   "already exists. Not safe — just clean.",
    ),
    ResearchItem(
        id="serving_infra", name="Inference-serving infrastructure", phase="tooling",
        duration_years=0.5, cash_cost=30, budget_fraction=0.20,
        contamination_tier=0.2, revenue_multiplier=1.2,
        what_it_does="Build out the serving stack — optimized inference, autoscaling, "
                     "deployment pipelines — so every model you ship reaches more users at "
                     "lower cost. Pure plumbing, but it turns the same model into more revenue.",
        risk_blurb="Plumbing carries no contamination of its own, but it widens the blast "
                   "radius: it scales the reach of whatever you deploy — a misaligned model "
                   "included — to far more users.",
    ),
]

CAPABILITY_TREE_BY_ID = {item.id: item for item in CAPABILITY_TREE}

